# Project information
site_name: 'Global Open Facility Registry'
site_description: 'GOFR Documentation'
site_author: 'IntraHealth'
site_url: 'https://github.com/intrahealth/gofr'

# Repository
repo_name: 'intrahealth/gofr'
repo_url: 'https://github.com/intrahealth/gofr'

# Copyright
copyright: 'Copyright &copy; 2022 IntraHealth International'

# Theme
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  icon:
    logo: material/library
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Noto Sans HK'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.sections
  favicon: favicon.png

nav:
  - Home: index.md
  - User Guide:
      - user_guide/introduction.md
      - user_guide/data_sources.md
      - user_guide/partitions.md
      - user_guide/facility_reconciliation.md
      - user_guide/facility_registry.md
      - user_guide/configure_system.md
      - user_guide/user_management.md

  - Developer Guide:
      - developer_guide/getting_started.md
      - developer_guide/architechture.md
      - developer_guide/load_query.md
      - developer_guide/working_with_fhir.md
      - developer_guide/mcsd.md
      - developer_guide/forms.md
      - developer_guide/ansible.md
      - developer_guide/gofr_installation.md
      - developer_guide/server_administration.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - admonition
  - footnotes
  - md_in_html
  - attr_list
  # - codehilite
  - toc:
      toc_depth: 2
      permalink: true

# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin not working
plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video
  - mknotebooks
  - mkdocstrings
  # - pdf-export:
  #     combined: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/intrahealth/gofr
